### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by L0SER8228** [itsnporg/Hacktoberfest-2021#1]
Could you please add some examples. I don't understand what should we have to contribute on .
I would be great, if you add some examples or a template

**Comment by thenishantsapkota** [comment]
Ok Thanks for Letting me know!
 I will add some examples!

**Comment by diwash007** [comment]
Does this repo satisfy for hactoberfest? 
I don't see any thing based on their requirements

**Comment by thenishantsapkota** [comment]
According to Hacktoberfest, 
Your pull requests will count toward your participation if they are in a repository with the 'hacktoberfest 'topic and once they have been merged, approved by a maintainer or labeled as **hacktoberfest-accepted**. 

Additionally, any pull request with the **hacktoberfest-accepted** label, submitted to any public GitHub/GitLab repository, with or without the hacktoberfest topic, will be considered valid for Hacktoberfest.

**Comment by thenishantsapkota** [comment]
> Could you please add some examples. I don't understand what should we have to contribute on . I would be great, if you add some examples or a template

You can take a look at this repository for examples.
Our goals are similar to theirs.
Link - https://github.com/ambujraj/hacktoberfest2018

**Comment by santoshkakkera** [comment]
hello @thenishantsapkota i am beginner and i can implement linear search ,binary search ,linked lists and all sorting algorithms .could you please assign me the task.
