### ISSUE TITLE
FIND FREQUENCY OF ELEMENTS IN A GIVEN ARRAY

### ISSUE THREAD

**Issue by Ananya02850** [itsnporg/Hacktoberfest-2021#306]
I would like to write code for this one

**Comment by PrajwalCH** [comment]
Yep you can.
Choose you language of favor and pull request 😁

**Comment by thenishantsapkota** [comment]
> Yep you can. Choose you language of favor and make a pull request 😁

This is the conventional way of making pull requests and ensuring that other users are not doing your part of the Pull request.

**Comment by susheel-kumar-1998** [comment]
I would like to write code in java

**Comment by mugdhapendse** [comment]
Hello! I'd like to contribute to this, I'll be writing the code in python!

**Comment by som-bit** [comment]
I would like to code this in a java.

**Comment by cmvyas** [comment]
I code in java and i will love to solve this issue, please assign it to me.
