### ISSUE TITLE
Insertion, Deletion and Traversal in Linked Lists

### ISSUE THREAD

**Issue by karandeeppotato** [itsnporg/Hacktoberfest-2021#75]
Hey there, I am willing to contribute a code on insertion, deletion, and traversal in linked lists.
Can you please assign me? 😉

**Comment by karandeeppotato** [comment]
Hello there, Please consider this PR #265

**Comment by som-bit** [comment]
I would like to code this in java

**Comment by tandrimasingha** [comment]
Name: Tandrima Singha
Hello @karandeeppotato Sir 
Please assign me this issue. I can do it in both python and java.

**Comment by karandeeppotato** [comment]
@tandrimasingha 
Unfortunately i cannot assign you because i am also a contributor here 😅.

You should ask @thenishantsapkota
